# -*- mode: python; -*-
cc_library(
    name = "hittop",
    hdrs = [
        "assert.h",
    ],
    srcs = [
    ],
    copts = ["-std=c++14"],
    deps = [
        "@boost//:headers",
    ],
    visibility = ["//visibility:public"]
)
